---
apiVersion: v1
kind: Service
metadata:
  name:sourcegraph-srv
spec:
  selector:
     app: sourcegraph
  ports:
  - protocol: TCP
    port: 7080
    targetPort: defaultport
  - protocol: TCP
    port: 2633
    targetPort: adminport
