apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - image: apache2
      name: apache2
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "mnt"
      effect: "NoSchedule"
